from setuptools import setup
import glob

requirements = [
    'tensorflow',
    'keras',
    'sqlalchemy',
    'opencv-contrib-python-headless',
    'requests',
    'PyQt5==5.14.2',
    'PyQtWebEngine==5.14',
    'scikit-learn',
    'flask',
    'fastcluster',
    'moviepy',
    'python-vlc',
    'librosa',
    'bokeh==2.2.1',
    'matplotlib',
    'numpy',
    'pysrt',
    'pymediainfo'
]

setup(
    name='VIAN',
    version='0.9.4',
    packages=['core',
              'core.gui',
              'core.gui.misc',
              'core.gui.dialogs',
              'core.gui.timeline',
              'core.data',
              'core.data.io',
              'core.misc',
              'core.analysis',
              'core.analysis.audio',
              'core.analysis.color',
              'core.analysis.motion',
              'core.analysis.colorimetry',
              'core.analysis.movie_mosaic',
              'core.analysis.eyetracking',
              'core.analysis.deep_learning',
              'core.analysis.pipeline_scripts',
              'core.container',
              'core.concurrent',
              'core.node_editor',
              'core.visualization',
              'extensions',
              'extensions.plugins',
              'extensions.plugins.fiwi_tools',
              'extensions.plugins.imdb_finder',
              'extensions.plugins.refactoring',
              'extensions.plugins.eyetracking_comparator',
              'extensions.scripts',
              'extensions.analysis',
              'extensions.pipelines', 'flask_server'],
    url='vian.app',
    license='GPL',
    author='Gaudenz Halter, Jonathan Schaber',
    author_email='',
    install_requires = requirements,
    description=''
)

