# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build_and_upload_VIAN

on:
  push:
    branches: [ develop ]

strategy:
  matrix:
    os: [macos-latest, windows-latest, ubuntu-latest]

jobs:
  build_application:
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller --onefile --name exetest123 vian/main.py
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_executable 
          path: dist/exetest123
          if-no-files-found: error

