# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build_and_upload_VIAN

on:
  push:
    branches: [ develop ]

jobs:
  build_application:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - run: pip install pyinstaller
      - run: cd vian
      - run: pyinstaller main.spec
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_executable 
          path: dist
          if-no-files-found: error

